name: continuosu deployment

on: 
  push:
    branches:
      - 'main'
    

jobs:
  docker-deployment:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_HOST_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ubuntu/entorno-sesion-8
          git pull 
          sudo docker compose down
          sudo docker rmi entorno-sesion-8-app
          mvn package -DskipTests
          sudo docker compose up -d